version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - C:\Users\Gramm\IdeaProjects\AutoTests\data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=VSXDUE